export MONGODB_URI="mongodb://amp:horizons1@ds117495.mlab.com:17495/free-assoc"
export SECRET="qwerty"
export GOOGLE_API_KEY="AIzaSyAs7riE2xT80wzGfYJq8SpjisLjDvSNeZA"
export AWS_ACCESS_KEY_ID="AKIAIEHNYE4AZEWOBQCQ"
export AWS_SECRET_ACCESS_KEY="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"
